#! /bin/sh
### BEGIN INIT INFO
# Provides:       fablab-door
# Required-Start: $network $named $syslog $time
# Should-Start: 
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description:    start the fablab door service
### END INIT INFO

# Author: Gaetan Collaud <gaetancollaud@gmail.com>
#

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Fablab door service"
NAME=fablab-door
DAEMON=/usr/bin/java
DAEMON_ARGS="-jar /fablab/fablab-door.jar"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

do_start() {
	if ps -p $(cat $PIDFILE) > /dev/null
	then
		echo "Already running"
	else	
		echo "Starting application"
		# Start application
		$DAEMON $DAEMON_ARGS > /dev/null &
		PID=$!
		echo $PID > $PIDFILE
	fi
}

do_stop() {
	echo "Stoppring application"
	#kill application
	kill $(cat $PIDFILE) > /dev/null
	sleep 1
}



case "$1" in
  start)
	do_start
	;;
  stop)
	echo "Stopping $DESC" "$NAME"
	do_stop
	;;
  restart)
	echo "Restarting $DESC" "$NAME"
	do_stop
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
